package com.asking.pad.app.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.asking.pad.app.entity.BookInfo;
import com.asking.pad.app.entity.classmedia.ClassMediaTable;
import com.asking.pad.app.entity.classmedia.StudyRecord;

import com.asking.pad.app.greendao.BookInfoDao;
import com.asking.pad.app.greendao.ClassMediaTableDao;
import com.asking.pad.app.greendao.StudyRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookInfoDaoConfig;
    private final DaoConfig classMediaTableDaoConfig;
    private final DaoConfig studyRecordDaoConfig;

    private final BookInfoDao bookInfoDao;
    private final ClassMediaTableDao classMediaTableDao;
    private final StudyRecordDao studyRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookInfoDaoConfig = daoConfigMap.get(BookInfoDao.class).clone();
        bookInfoDaoConfig.initIdentityScope(type);

        classMediaTableDaoConfig = daoConfigMap.get(ClassMediaTableDao.class).clone();
        classMediaTableDaoConfig.initIdentityScope(type);

        studyRecordDaoConfig = daoConfigMap.get(StudyRecordDao.class).clone();
        studyRecordDaoConfig.initIdentityScope(type);

        bookInfoDao = new BookInfoDao(bookInfoDaoConfig, this);
        classMediaTableDao = new ClassMediaTableDao(classMediaTableDaoConfig, this);
        studyRecordDao = new StudyRecordDao(studyRecordDaoConfig, this);

        registerDao(BookInfo.class, bookInfoDao);
        registerDao(ClassMediaTable.class, classMediaTableDao);
        registerDao(StudyRecord.class, studyRecordDao);
    }
    
    public void clear() {
        bookInfoDaoConfig.clearIdentityScope();
        classMediaTableDaoConfig.clearIdentityScope();
        studyRecordDaoConfig.clearIdentityScope();
    }

    public BookInfoDao getBookInfoDao() {
        return bookInfoDao;
    }

    public ClassMediaTableDao getClassMediaTableDao() {
        return classMediaTableDao;
    }

    public StudyRecordDao getStudyRecordDao() {
        return studyRecordDao;
    }

}
