package com.asking.pad.app.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.asking.pad.app.entity.book.BookDownInfo;
import com.asking.pad.app.entity.book.BookTable;
import com.asking.pad.app.entity.classmedia.ClassMediaTable;
import com.asking.pad.app.entity.classmedia.StudyRecord;

import com.asking.pad.app.greendao.BookDownInfoDao;
import com.asking.pad.app.greendao.BookTableDao;
import com.asking.pad.app.greendao.ClassMediaTableDao;
import com.asking.pad.app.greendao.StudyRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDownInfoDaoConfig;
    private final DaoConfig bookTableDaoConfig;
    private final DaoConfig classMediaTableDaoConfig;
    private final DaoConfig studyRecordDaoConfig;

    private final BookDownInfoDao bookDownInfoDao;
    private final BookTableDao bookTableDao;
    private final ClassMediaTableDao classMediaTableDao;
    private final StudyRecordDao studyRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDownInfoDaoConfig = daoConfigMap.get(BookDownInfoDao.class).clone();
        bookDownInfoDaoConfig.initIdentityScope(type);

        bookTableDaoConfig = daoConfigMap.get(BookTableDao.class).clone();
        bookTableDaoConfig.initIdentityScope(type);

        classMediaTableDaoConfig = daoConfigMap.get(ClassMediaTableDao.class).clone();
        classMediaTableDaoConfig.initIdentityScope(type);

        studyRecordDaoConfig = daoConfigMap.get(StudyRecordDao.class).clone();
        studyRecordDaoConfig.initIdentityScope(type);

        bookDownInfoDao = new BookDownInfoDao(bookDownInfoDaoConfig, this);
        bookTableDao = new BookTableDao(bookTableDaoConfig, this);
        classMediaTableDao = new ClassMediaTableDao(classMediaTableDaoConfig, this);
        studyRecordDao = new StudyRecordDao(studyRecordDaoConfig, this);

        registerDao(BookDownInfo.class, bookDownInfoDao);
        registerDao(BookTable.class, bookTableDao);
        registerDao(ClassMediaTable.class, classMediaTableDao);
        registerDao(StudyRecord.class, studyRecordDao);
    }
    
    public void clear() {
        bookDownInfoDaoConfig.clearIdentityScope();
        bookTableDaoConfig.clearIdentityScope();
        classMediaTableDaoConfig.clearIdentityScope();
        studyRecordDaoConfig.clearIdentityScope();
    }

    public BookDownInfoDao getBookDownInfoDao() {
        return bookDownInfoDao;
    }

    public BookTableDao getBookTableDao() {
        return bookTableDao;
    }

    public ClassMediaTableDao getClassMediaTableDao() {
        return classMediaTableDao;
    }

    public StudyRecordDao getStudyRecordDao() {
        return studyRecordDao;
    }

}
